# Generated by Django 6.0.4 on 2026-04-20 07:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("core", "0003_driverstate_singleton")]

    operations = [
        migrations.AddField(
            model_name="user",
            name="can_upload",
            field=models.BooleanField(default=False),
        )
    ]
