# Generated by Django 6.0.4 on 2026-06-27 11:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [("core", "0004_user_can_upload")]

    operations = [migrations.DeleteModel(name="Collection")]
