# Generated by Django 6.0.4 on 2026-06-27 11:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("core", "0005_delete_collection")]

    operations = [
        migrations.AddField(
            model_name="box", name="immich_album_url", field=models.URLField(blank=True)
        ),
        migrations.AddField(
            model_name="box", name="immich_error", field=models.TextField(blank=True)
        ),
        migrations.AddField(
            model_name="box",
            name="immich_state",
            field=models.CharField(
                choices=[
                    ("not_uploaded", "Nicht hochgeladen"),
                    ("in_progress", "Wird hochgeladen"),
                    ("uploaded", "Hochgeladen"),
                    ("failed", "Fehlgeschlagen"),
                ],
                default="not_uploaded",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="image",
            name="immich_asset_id",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="image",
            name="immich_checksum",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="image",
            name="immich_owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="immich_uploads",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="image",
            name="immich_signature",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="image",
            name="immich_uploaded_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="immich_api_key",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
