# Generated by Django 6.0.6 on 2026-06-27 17:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("core", "0006_box_immich_album_url_box_immich_error_and_more")]

    operations = [
        migrations.AddField(
            model_name="image",
            name="latitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
        migrations.AddField(
            model_name="image",
            name="longitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
    ]
