# Generated by Django 6.0.6 on 2026-06-28 08:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("core", "0007_image_latitude_image_longitude")]

    operations = [
        migrations.AddField(
            model_name="user",
            name="api_token",
            field=models.CharField(
                blank=True, default=None, max_length=128, null=True, unique=True
            ),
        )
    ]
