# Generated by Django 6.0.6 on 2026-06-28 09:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("core", "0008_user_api_token")]

    operations = [
        migrations.AddField(
            model_name="image",
            name="immich_capture_datetime",
            field=models.CharField(blank=True, max_length=40),
        )
    ]
