# Generated by Django 6.0.6 on 2026-07-22 17:59

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("core", "0009_image_immich_capture_datetime")]

    operations = [
        migrations.CreateModel(
            name="ImmichEditSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("state", models.CharField(default="pending", max_length=10)),
                ("data", models.JSONField(default=list)),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="immich_edit_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        )
    ]
